#pragma once

// RX
#define VISION_TURN_SIGNALS_COMMAND_RX
#define VISION_BRAKE_LIGHTS_COMMAND_RX
#define VISION_HEADLIGHTS_COMMAND_RX
#define BMS_KILL_REASON_RX

// TX
#define VISION_STATUS_FRONT_TX
#define VISION_STATUS_REAR_TX
#define LIGHTS_FRONT_ID_TX
#define LIGHTS_BACK_ID_TX